---
abstract: 'Help validate CGI::Application run modes using Data::FormValidator'
author:
  - 'Mark Stosberg <mark@summersault.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-ValidateRM
provides:
  CGI::Application::Plugin::ValidateRM:
    file: lib/CGI/Application/Plugin/ValidateRM.pm
    version: 2.51
requires:
  CGI::Application: 3
  Data::FormValidator: 3.7
  HTML::FillInForm: 1.07
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/fany/CGI-Application-Plugin-ValidateRM
version: 2.51
